const crypto = require('crypto');
const config = require('../config/env');

/**
 * License Signer Service
 * Pluggable Cryptographic License Engine (Ready for HSM/KMS integration)
 */
class LicenseSignerService {
  constructor() {
    this.signingKeyId = 'KAVACHIQ-KMS-ROOT-V1';
    this.secret = config.LICENSE_SIGNING_SECRET;
  }

  /**
   * Generate a unique human-readable License Key
   * e.g., KAV-NMS-ENT-7492-4821-X99B
   */
  generateLicenseKey(productCode, editionCode) {
    const p = (productCode || 'GEN').substring(0, 3).toUpperCase();
    const e = (editionCode || 'STD').substring(0, 3).toUpperCase();
    const rand1 = crypto.randomBytes(2).toString('hex').toUpperCase();
    const rand2 = crypto.randomBytes(2).toString('hex').toUpperCase();
    const rand3 = crypto.randomBytes(2).toString('hex').toUpperCase();
    return `KAV-${p}-${e}-${rand1}-${rand2}-${rand3}`;
  }

  /**
   * Cryptographically sign the license payload
   * In a production HSM setup, this calls AWS KMS, HashiCorp Vault, or an On-Prem HSM PKCS#11 module.
   */
  signLicense(payload, customKeyId = null) {
    const keyId = customKeyId || this.signingKeyId;
    const timestamp = new Date().toISOString();

    const canonicalData = {
      ...payload,
      meta: {
        issuer: 'GTS TECHNOSOFT AI LLP - KavachIQ Licensing Authority',
        key_id: keyId,
        issued_at: timestamp,
        schema_version: '2.4.0'
      }
    };

    const payloadJson = JSON.stringify(canonicalData);
    const hmac = crypto.createHmac('sha256', this.secret);
    hmac.update(payloadJson);
    const signature = hmac.digest('hex');

    const signedContainer = {
      algorithm: 'HMAC-SHA256-SIGN',
      key_id: keyId,
      issued_at: timestamp,
      signature: signature,
      payload_base64: Buffer.from(payloadJson).toString('base64')
    };

    const signedPayloadString = JSON.stringify(signedContainer, null, 2);

    return {
      signedPayload: signedPayloadString,
      signature: signature,
      keyId: keyId,
      payloadJson: canonicalData
    };
  }

  /**
   * Verify a signed license file or payload
   */
  verifyLicense(signedPayloadString) {
    try {
      const container = typeof signedPayloadString === 'string' 
        ? JSON.parse(signedPayloadString) 
        : signedPayloadString;

      if (!container.payload_base64 || !container.signature) {
        return { valid: false, reason: 'Invalid license format or missing signature' };
      }

      const decodedJson = Buffer.from(container.payload_base64, 'base64').toString('utf8');
      const hmac = crypto.createHmac('sha256', this.secret);
      hmac.update(decodedJson);
      const expectedSignature = hmac.digest('hex');

      if (crypto.timingSafeEqual(Buffer.from(container.signature), Buffer.from(expectedSignature))) {
        const payload = JSON.parse(decodedJson);
        const isExpired = payload.validity?.expires_at && new Date(payload.validity.expires_at) < new Date();
        return {
          valid: !isExpired,
          isExpired,
          payload,
          keyId: container.key_id,
          issuedAt: container.issued_at
        };
      }

      return { valid: false, reason: 'Cryptographic signature mismatch' };
    } catch (err) {
      return { valid: false, reason: `Verification error: ${err.message}` };
    }
  }

  /**
   * Format license file (.lic) output
   */
  generateLicFileContent(licenseRecord, org, product, edition) {
    const separator = '================================================================================';
    return `# ${separator}
# GTS TECHNOSOFT AI LLP - KAVACHIQ COMMERCIAL SOFTWARE LICENSE
# Product: ${product?.name || 'KavachIQ Software'} (${edition?.name || 'Standard'})
# Organization: ${org?.legal_name || 'Licensed Customer'}
# License Key: ${licenseRecord.license_key}
# Expiration: ${new Date(licenseRecord.expiry_date).toISOString()}
# Status: ${licenseRecord.status}
# ${separator}
# DO NOT EDIT THIS FILE. TAMPERING INVALIDATES THE CRYPTOGRAPHIC INTEGRITY.
# ${separator}

-----BEGIN KAVACHIQ ENCRYPTED LICENSE CONTAINER-----
${licenseRecord.signed_payload}
-----END KAVACHIQ ENCRYPTED LICENSE CONTAINER-----
`;
  }
}

module.exports = new LicenseSignerService();
